import { callGemini } from './gemini.js';
import { callOpenRouter } from './openrouter.js';
import { getCache, setCache } from '../utils/cache.js';

// Complete domain-specific fallback questions for all 9 domains
const domainFallbacks = {

    'Frontend Development': {
        beginner: [
            { id: 1, level: 'beginner', type: 'conceptual', question: 'What is the difference between HTML, CSS, and JavaScript?', answer: 'HTML defines the structure and content of a webpage using elements like headings, paragraphs, and links. CSS controls the visual presentation — colors, fonts, layout, and spacing. JavaScript adds interactivity and dynamic behavior, allowing pages to respond to user actions, fetch data, and update content without reloading. Together they form the three core layers of frontend development: structure, style, and behavior.', hint: 'Think of HTML as the skeleton, CSS as the skin, and JavaScript as the muscles.' },
            { id: 2, level: 'beginner', type: 'conceptual', question: 'What is the Virtual DOM in React and why is it used?', answer: 'The Virtual DOM is a lightweight in-memory representation of the real DOM. When state changes, React updates the Virtual DOM first, compares it with the previous snapshot (diffing), and applies only the minimal changes to the real DOM (reconciliation). This improves performance because direct DOM manipulation is expensive, and batching updates through the Virtual DOM reduces unnecessary re-renders.', hint: 'Think about why directly manipulating the real DOM is slow.' },
            { id: 3, level: 'beginner', type: 'coding', question: 'Write a JavaScript function to flatten a nested array one level deep.', answer: 'Use Array.flat(): const flatten = arr => arr.flat(). Manual approach: const flatten = arr => arr.reduce((acc, val) => acc.concat(val), []). The reduce approach iterates each element and concatenates arrays into the accumulator. Time complexity is O(n). For deep flattening use arr.flat(Infinity).', hint: 'Try Array.reduce() or the spread operator inside a loop.' },
        ],
        intermediate: [
            { id: 4, level: 'intermediate', type: 'conceptual', question: 'Explain the difference between controlled and uncontrolled components in React.', answer: 'A controlled component has its form element value managed by React state — the input value is set via state and updated via onChange. An uncontrolled component stores its own state internally in the DOM, accessed via refs. Controlled components are preferred because they make validation and enforcing input formats straightforward. Uncontrolled components are simpler for basic forms or when integrating with non-React code.', hint: 'Ask yourself: who owns the form data — React state or the DOM?' },
            { id: 5, level: 'intermediate', type: 'coding', question: 'Implement a debounce function in JavaScript.', answer: 'function debounce(fn, delay) { let timer; return function(...args) { clearTimeout(timer); timer = setTimeout(() => fn.apply(this, args), delay); }; }. This delays invoking a function until after a wait time has elapsed since the last call. Commonly used for search inputs to avoid firing an API call on every keystroke. Each new call resets the timer.', hint: 'Use setTimeout and clearTimeout — clear the previous timer on each new call.' },
            { id: 6, level: 'intermediate', type: 'conceptual', question: 'What is CSS specificity and how is it calculated?', answer: 'CSS specificity determines which style rule applies when multiple rules target the same element. It is calculated as a 4-part value: inline styles (1,0,0,0), IDs (0,1,0,0), classes/attributes/pseudo-classes (0,0,1,0), and elements/pseudo-elements (0,0,0,1). The rule with the highest specificity wins. If equal, the last rule in the stylesheet wins. The !important declaration overrides all specificity rules.', hint: 'Remember the hierarchy: inline > ID > class > element.' },
            { id: 7, level: 'intermediate', type: 'conceptual', question: 'What are React hooks and why were they introduced?', answer: 'React hooks are functions that let you use state and other React features in functional components, introduced in React 16.8. Key hooks include useState (local state), useEffect (side effects), useContext (consuming context), useRef (DOM references), and useMemo/useCallback (performance). Hooks were introduced to solve problems with class components: complex lifecycle methods, difficulty reusing stateful logic, and confusing "this" binding.', hint: 'Think about what problems class components had that hooks solve.' },
        ],
        advanced: [
            { id: 8, level: 'advanced', type: 'conceptual', question: "Explain React's reconciliation algorithm and how keys help optimize it.", answer: "React's reconciliation algorithm compares the new Virtual DOM tree with the previous one to determine the minimal DOM operations needed. It uses a heuristic O(n) algorithm. When rendering lists, keys help React identify which items changed, were added, or removed — without keys React re-renders the entire list. Keys should be stable unique IDs, not array indices, to avoid bugs when items are reordered.", hint: 'Consider what happens when React compares two lists without keys vs with keys.' },
            { id: 9, level: 'advanced', type: 'conceptual', question: 'What are Web Workers and when would you use them?', answer: 'Web Workers allow JavaScript to run in background threads separate from the main UI thread, preventing heavy computations from blocking rendering and user interactions. They communicate via postMessage and onmessage events. Use cases include parsing large JSON datasets, image processing, complex calculations, and running WebAssembly. Limitations include no access to the DOM or localStorage. Use them only when profiling reveals main thread blocking.', hint: 'Think about what happens to the UI when JavaScript runs a heavy loop for several seconds.' },
            { id: 10, level: 'advanced', type: 'conceptual', question: 'How would you optimize a React application that renders large lists?', answer: 'Key strategies: (1) Virtualization — use react-window to render only visible items; (2) Memoization — wrap list items in React.memo; (3) useCallback/useMemo — stabilize callback references; (4) Code splitting — use React.lazy and Suspense; (5) Avoid anonymous functions in JSX; (6) Use stable keys; (7) Pagination or infinite scroll. Always profile with React DevTools Profiler before optimizing.', hint: 'Start with virtualization for large lists — it is the biggest win.' },
        ],
    },

    'Backend Development': {
        beginner: [
            { id: 1, level: 'beginner', type: 'conceptual', question: 'What is REST and what are the main HTTP methods used in RESTful APIs?', answer: 'REST (Representational State Transfer) is an architectural style for building web APIs based on stateless client-server communication. The main HTTP methods are: GET (retrieve), POST (create), PUT (replace), PATCH (partial update), and DELETE (remove). RESTful APIs use URLs to identify resources and HTTP methods to define the action. Responses use JSON format and standard HTTP status codes like 200 OK, 201 Created, 404 Not Found.', hint: 'Map CRUD to HTTP: Create=POST, Read=GET, Update=PUT/PATCH, Delete=DELETE.' },
            { id: 2, level: 'beginner', type: 'conceptual', question: 'What is middleware in Express.js and how does it work?', answer: 'Middleware in Express.js are functions with access to req, res, and next. They can execute code, modify req/res, end the request-response cycle, or call next() to pass control forward. They execute in the order defined. Common uses include logging, parsing bodies (express.json()), authentication checks, error handling, and CORS headers. The chain stops when a response is sent or an error is thrown.', hint: 'Think of middleware as a pipeline — each function processes the request and passes it along.' },
            { id: 3, level: 'beginner', type: 'coding', question: 'Write an Express.js POST route that validates input and returns JSON.', answer: 'app.use(express.json()); app.post("/api/users", (req, res) => { const { name, email } = req.body; if (!name || !email) return res.status(400).json({ error: "Name and email required" }); res.status(201).json({ success: true, user: { id: Date.now(), name, email } }); }). Key points: express.json() must be added before routes, use req.body to access parsed data, return appropriate HTTP status codes, and always validate input.', hint: 'Remember to add express.json() middleware before your route handler.' },
        ],
        intermediate: [
            { id: 4, level: 'intermediate', type: 'conceptual', question: 'What is JWT authentication and how does it work?', answer: 'JWT (JSON Web Token) is a compact token for securely transmitting information. It has three Base64URL-encoded parts: Header (algorithm), Payload (claims like userId, expiry), and Signature (HMAC of header+payload). Flow: user logs in → server verifies credentials → creates signed JWT → client stores it → sends in Authorization header → server verifies signature without a database lookup. JWTs are stateless, ideal for distributed systems. Never store sensitive data in the payload as it is only signed, not encrypted.', hint: 'JWTs are signed not encrypted — the payload is readable by anyone.' },
            { id: 5, level: 'intermediate', type: 'coding', question: 'Implement a simple rate limiter middleware in Node.js.', answer: 'const rateLimiter = (max, windowMs) => { const map = new Map(); return (req, res, next) => { const ip = req.ip; const now = Date.now(); const times = (map.get(ip) || []).filter(t => t > now - windowMs); if (times.length >= max) return res.status(429).json({ error: "Too many requests" }); times.push(now); map.set(ip, times); next(); }; }; app.use(rateLimiter(100, 60000)). This uses a sliding window — storing timestamps per IP and filtering expired ones. For production use Redis to share state across instances.', hint: 'Store request timestamps per IP and count how many fall within the time window.' },
            { id: 6, level: 'intermediate', type: 'conceptual', question: 'Explain SQL vs NoSQL databases with use cases.', answer: 'SQL databases (PostgreSQL, MySQL) are relational with predefined schemas, foreign key relationships, and ACID transactions — best for financial systems, e-commerce, and user accounts with complex relationships. NoSQL databases (MongoDB, Redis, Cassandra) have flexible schemas and horizontal scaling — MongoDB stores JSON-like documents, Redis stores key-value pairs in memory, Cassandra handles time-series data at scale. Best for real-time analytics, content management, caching, and IoT. Many apps use both (polyglot persistence).', hint: 'Consider data structure, consistency requirements, and scale.' },
            { id: 7, level: 'intermediate', type: 'conceptual', question: 'What is database indexing and when should you use it?', answer: 'A database index is a data structure (typically B-tree) that speeds up data retrieval at the cost of storage and slower writes. Without an index, queries scan every row. With an index, the database jumps directly to matching rows. Use indexes on columns in WHERE clauses, JOIN conditions, ORDER BY, and foreign keys. Avoid over-indexing — each index slows INSERT/UPDATE/DELETE. Composite indexes cover multi-column queries. Use EXPLAIN to analyze query plans.', hint: 'Indexes speed up reads but slow down writes — use on frequently queried columns.' },
        ],
        advanced: [
            { id: 8, level: 'advanced', type: 'conceptual', question: 'How would you design a scalable microservices architecture?', answer: 'Key components: (1) API Gateway — single entry point for routing, auth, rate limiting; (2) Service Discovery — Consul or Kubernetes DNS; (3) Message Queue — Kafka or RabbitMQ for async communication; (4) Circuit Breaker — prevent cascade failures; (5) Distributed Tracing — Jaeger or Zipkin; (6) Centralized Logging — ELK stack; (7) Container Orchestration — Kubernetes; (8) Database per service for loose coupling. Start with a monolith and extract services as boundaries become clear.', hint: 'Think about service discovery, communication patterns, and failure handling.' },
            { id: 9, level: 'advanced', type: 'conceptual', question: 'Explain database transaction isolation levels.', answer: 'Isolation levels control how transactions interact: (1) Read Uncommitted — can read uncommitted changes (dirty reads), fastest but least safe; (2) Read Committed (PostgreSQL default) — only reads committed data; (3) Repeatable Read (MySQL default) — same row read twice returns same data; (4) Serializable — transactions execute as if sequential, prevents all anomalies but slowest. For financial transactions use Serializable. For analytics dashboards, Read Committed is usually sufficient. Higher isolation means more locking and lower throughput.', hint: 'Higher isolation prevents more anomalies but reduces concurrency.' },
            { id: 10, level: 'advanced', type: 'conceptual', question: 'How would you handle 10,000 concurrent WebSocket connections in Node.js?', answer: 'Node.js is well-suited for WebSockets due to its event-driven non-blocking I/O. Strategies: (1) Use ws or Socket.io library; (2) Cluster module or PM2 to use all CPU cores; (3) Redis Pub/Sub with socket.io-redis adapter to broadcast across instances; (4) Heartbeat/ping-pong to detect dead connections; (5) Message batching to reduce overhead; (6) Horizontal scaling with sticky sessions or shared Redis state; (7) Monitor memory — each connection holds state; (8) Use binary protocols for high-frequency messages.', hint: 'Think about clustering, shared state with Redis, and connection lifecycle.' },
        ],
    },

    'Full Stack Development': {
        beginner: [
            { id: 1, level: 'beginner', type: 'conceptual', question: 'What is the MERN stack and what does each technology do?', answer: 'MERN stands for MongoDB, Express.js, React, and Node.js. MongoDB is a NoSQL document database that stores data as JSON-like documents. Express.js is a minimal Node.js web framework for building REST APIs. React is a JavaScript library for building interactive user interfaces using components. Node.js is a JavaScript runtime that allows running JavaScript on the server side. Together they allow building full-stack web applications using JavaScript throughout the entire stack, from database to frontend.', hint: 'Think about what role each layer plays: database, server, UI, and runtime.' },
            { id: 2, level: 'beginner', type: 'conceptual', question: 'What is the difference between frontend and backend development?', answer: 'Frontend development deals with everything the user sees and interacts with in the browser — HTML structure, CSS styling, and JavaScript behavior. It focuses on user experience, responsiveness, and performance in the browser. Backend development handles server-side logic, databases, authentication, and APIs that the frontend consumes. It runs on a server and is not visible to users. Full stack developers work on both layers, understanding how data flows from the database through the API to the user interface.', hint: 'Frontend is what users see; backend is what powers it behind the scenes.' },
            { id: 3, level: 'beginner', type: 'coding', question: 'Write a simple Express API endpoint that returns a list of users from an array.', answer: 'const express = require("express"); const app = express(); const users = [{ id: 1, name: "Alice" }, { id: 2, name: "Bob" }]; app.get("/api/users", (req, res) => { res.json({ success: true, users }); }); app.listen(3000, () => console.log("Server running")). This creates a GET endpoint at /api/users that returns the users array as JSON. In a real app, you would replace the array with a database query using Mongoose or another ORM.', hint: 'Use res.json() to send JSON responses and define the route with app.get().' },
        ],
        intermediate: [
            { id: 4, level: 'intermediate', type: 'conceptual', question: 'How does authentication work in a full stack MERN application?', answer: 'In a MERN app, authentication typically uses JWT tokens. The flow: user submits login form (React) → POST request to Express API → server validates credentials against MongoDB → if valid, server signs a JWT with a secret key and returns it → React stores the token in localStorage or a cookie → subsequent API requests include the token in the Authorization header → Express middleware verifies the token on protected routes. Libraries like bcrypt hash passwords before storing, and jsonwebtoken handles JWT creation and verification.', hint: 'Think about the complete flow from login form to protected API route.' },
            { id: 5, level: 'intermediate', type: 'coding', question: 'How do you connect a React frontend to an Express backend and handle CORS?', answer: 'In Express, install and configure cors: const cors = require("cors"); app.use(cors({ origin: "http://localhost:3000" })). In React, use fetch or axios to call the API: const res = await axios.get("http://localhost:5000/api/users"). For production, set the origin to your actual domain. During development, you can also configure a proxy in package.json: "proxy": "http://localhost:5000" — this lets React make requests to /api/users without specifying the full URL, and the dev server proxies them to Express.', hint: 'CORS must be enabled on the server; the proxy setting helps during development.' },
            { id: 6, level: 'intermediate', type: 'conceptual', question: 'What is Mongoose and how does it simplify working with MongoDB?', answer: 'Mongoose is an ODM (Object Document Mapper) for MongoDB and Node.js. It provides a schema-based solution to model application data, adding structure to MongoDB\'s flexible documents. Key features: Schema definition (define fields, types, validation rules), Models (classes that represent MongoDB collections), built-in validation, middleware (pre/post hooks for save, find, etc.), and query building with a chainable API. Without Mongoose you work with raw MongoDB driver which requires more boilerplate. Mongoose makes it easier to enforce data consistency and write cleaner database code.', hint: 'Think of Mongoose as adding structure and validation on top of MongoDB.' },
            { id: 7, level: 'intermediate', type: 'conceptual', question: 'What is the difference between server-side rendering (SSR) and client-side rendering (CSR)?', answer: 'In CSR (like standard React), the browser downloads a minimal HTML file and a JavaScript bundle, then React renders the UI in the browser. This means the initial page load shows a blank screen until JS loads. In SSR (like Next.js), the server renders the full HTML for each request and sends it to the browser — users see content immediately and SEO crawlers can index it. SSR improves initial load performance and SEO but increases server load. CSR is simpler and better for highly interactive apps after the initial load. Next.js supports both approaches per page.', hint: 'Consider who does the rendering — the server or the browser — and the trade-offs.' },
        ],
        advanced: [
            { id: 8, level: 'advanced', type: 'conceptual', question: 'How would you implement real-time features in a MERN application?', answer: 'Real-time features can be implemented using WebSockets via Socket.io. Setup: install socket.io on Express server and socket.io-client in React. Server emits events (io.emit or socket.emit) and clients listen for them. For chat: client sends message → server receives and broadcasts to all connected clients → all React clients update their state. For scalability with multiple server instances, use Redis adapter (socket.io-redis) to share events across instances. Alternatively, use Server-Sent Events (SSE) for one-way real-time updates like notifications.', hint: 'Socket.io abstracts WebSockets and provides rooms, namespaces, and fallbacks.' },
            { id: 9, level: 'advanced', type: 'conceptual', question: 'What strategies would you use to deploy and scale a MERN application?', answer: 'Deployment strategies: (1) Containerize with Docker — create Dockerfiles for frontend and backend, use docker-compose for local development; (2) Deploy backend to cloud (AWS EC2, Railway, Render) and frontend to CDN (Vercel, Netlify); (3) Use MongoDB Atlas for managed database hosting; (4) Set up CI/CD with GitHub Actions to automate testing and deployment; (5) Use PM2 or cluster mode for Node.js to utilize multiple CPU cores; (6) Add a reverse proxy (Nginx) in front of Node.js; (7) Use environment variables for all secrets; (8) Set up monitoring with tools like Datadog or New Relic.', hint: 'Think about containerization, managed services, CI/CD, and horizontal scaling.' },
            { id: 10, level: 'advanced', type: 'conceptual', question: 'How do you handle state management in a large React application?', answer: 'For large apps, local useState becomes insufficient. Options: (1) Context API — built-in React solution for sharing state without prop drilling, good for auth/theme; (2) Redux Toolkit — industry standard for complex state, provides predictable state container with DevTools; (3) Zustand — lightweight alternative to Redux with simpler API; (4) React Query / TanStack Query — specialized for server state (caching, background refetching, optimistic updates); (5) Jotai or Recoil — atomic state management. Best practice: use React Query for server state and Zustand/Redux for client state, avoiding storing server data in Redux.', hint: 'Distinguish between server state (API data) and client state (UI state) — they need different solutions.' },
        ],
    },

    'Data Analysis': {
        beginner: [
            { id: 1, level: 'beginner', type: 'conceptual', question: 'What is the difference between data analysis and data science?', answer: 'Data analysis focuses on examining existing datasets to answer specific business questions, identify trends, and generate actionable insights using tools like Excel, SQL, and Power BI. Data science is broader — it includes data analysis but also involves building predictive models using machine learning, statistical modeling, and programming (Python/R). Data analysts typically work with structured data and business reporting, while data scientists build algorithms and models to predict future outcomes. Both roles require strong analytical thinking and data literacy.', hint: 'Data analysis answers "what happened"; data science predicts "what will happen".' },
            { id: 2, level: 'beginner', type: 'conceptual', question: 'What is SQL and why is it essential for data analysis?', answer: 'SQL (Structured Query Language) is the standard language for querying and manipulating relational databases. It is essential for data analysis because most business data lives in relational databases (MySQL, PostgreSQL, SQL Server). Key SQL operations include SELECT (retrieve data), WHERE (filter rows), GROUP BY (aggregate data), JOIN (combine tables), and ORDER BY (sort results). Data analysts use SQL to extract, clean, and aggregate data before visualizing it. Even with tools like Power BI or Tableau, SQL knowledge is required to write custom queries and understand data sources.', hint: 'SQL is the primary tool for extracting data from relational databases.' },
            { id: 3, level: 'beginner', type: 'coding', question: 'Write a SQL query to find the top 5 customers by total purchase amount.', answer: 'SELECT customer_id, customer_name, SUM(purchase_amount) AS total_spent FROM orders JOIN customers ON orders.customer_id = customers.id GROUP BY customer_id, customer_name ORDER BY total_spent DESC LIMIT 5. This query joins the orders and customers tables, groups by customer, sums their purchase amounts, sorts in descending order, and limits to 5 results. The GROUP BY clause is essential when using aggregate functions like SUM. Always alias aggregate columns for readability.', hint: 'Use GROUP BY with SUM(), then ORDER BY DESC and LIMIT 5.' },
        ],
        intermediate: [
            { id: 4, level: 'intermediate', type: 'conceptual', question: 'What is the difference between OLTP and OLAP databases?', answer: 'OLTP (Online Transaction Processing) databases are optimized for high-volume, short transactions — inserts, updates, and deletes. They are normalized to reduce redundancy and support day-to-day operations (e.g., order processing, banking). OLAP (Online Analytical Processing) databases are optimized for complex analytical queries across large datasets — aggregations, historical analysis, and reporting. They use denormalized star or snowflake schemas for faster reads. Data warehouses like Snowflake, BigQuery, and Redshift are OLAP systems. Data analysts primarily work with OLAP systems after data is ETL-processed from OLTP sources.', hint: 'OLTP is for transactions; OLAP is for analysis and reporting.' },
            { id: 5, level: 'intermediate', type: 'conceptual', question: 'What is ETL and why is it important in data analysis?', answer: 'ETL stands for Extract, Transform, Load — the process of moving data from source systems to a data warehouse. Extract: pull data from various sources (databases, APIs, files). Transform: clean, normalize, deduplicate, and reshape data into a consistent format. Load: insert the transformed data into the target data warehouse or database. ETL is critical because raw data from different sources is often inconsistent, dirty, or in incompatible formats. Tools like Apache Airflow, dbt, Talend, and AWS Glue automate ETL pipelines. Without ETL, analysts would spend most of their time cleaning data manually.', hint: 'ETL moves data from operational systems to analytical systems in a clean, usable format.' },
            { id: 6, level: 'intermediate', type: 'coding', question: 'Write a SQL query to calculate month-over-month revenue growth.', answer: 'WITH monthly AS (SELECT DATE_TRUNC("month", order_date) AS month, SUM(revenue) AS total FROM orders GROUP BY 1) SELECT month, total, LAG(total) OVER (ORDER BY month) AS prev_month, ROUND((total - LAG(total) OVER (ORDER BY month)) / LAG(total) OVER (ORDER BY month) * 100, 2) AS growth_pct FROM monthly ORDER BY month. This uses a CTE to aggregate monthly revenue, then the LAG window function to access the previous month value, calculating percentage growth. Window functions are essential for time-series analysis in SQL.', hint: 'Use LAG() window function to access the previous row value for comparison.' },
            { id: 7, level: 'intermediate', type: 'conceptual', question: 'What are the key metrics used in business data analysis?', answer: 'Common business metrics include: KPIs (Key Performance Indicators) — measurable values that demonstrate how effectively a company achieves objectives; Revenue metrics — MRR (Monthly Recurring Revenue), ARR, ARPU (Average Revenue Per User); Customer metrics — CAC (Customer Acquisition Cost), LTV (Lifetime Value), churn rate, NPS (Net Promoter Score); Operational metrics — conversion rate, bounce rate, DAU/MAU (Daily/Monthly Active Users); Financial metrics — gross margin, EBITDA, burn rate. Analysts must understand which metrics matter for each business context and how to calculate them accurately from raw data.', hint: 'Think about metrics across revenue, customers, operations, and finance.' },
        ],
        advanced: [
            { id: 8, level: 'advanced', type: 'conceptual', question: 'How would you design a data pipeline for real-time analytics?', answer: 'A real-time analytics pipeline typically uses: (1) Data ingestion — Kafka or AWS Kinesis to stream events from applications; (2) Stream processing — Apache Flink or Spark Streaming to process and aggregate events in real-time; (3) Storage — write to a time-series database (InfluxDB) or columnar store (ClickHouse) optimized for fast reads; (4) Serving layer — REST API or GraphQL to expose aggregated metrics; (5) Visualization — Grafana or custom dashboards. Key challenges include handling late-arriving data, exactly-once processing semantics, and scaling to millions of events per second. Start with batch processing and migrate to streaming as latency requirements tighten.', hint: 'Think about ingestion, processing, storage, and serving layers separately.' },
            { id: 9, level: 'advanced', type: 'conceptual', question: 'What is A/B testing and how do you ensure statistical validity?', answer: 'A/B testing compares two versions of something (webpage, feature, email) to determine which performs better. To ensure statistical validity: (1) Define a clear hypothesis and primary metric before starting; (2) Calculate required sample size using power analysis (typically 80% power, 95% confidence); (3) Randomly assign users to control (A) and treatment (B) groups; (4) Run the test for a full business cycle to avoid day-of-week bias; (5) Use a t-test or chi-square test to calculate p-value; (6) Only declare a winner if p-value < 0.05 (or your chosen significance level); (7) Watch for novelty effects and multiple testing problems (Bonferroni correction). Never stop a test early because it looks significant.', hint: 'Focus on sample size, randomization, statistical significance, and avoiding common pitfalls.' },
            { id: 10, level: 'advanced', type: 'conceptual', question: 'How do you handle missing data and outliers in a dataset?', answer: 'For missing data: (1) Understand why data is missing — MCAR (Missing Completely At Random), MAR, or MNAR; (2) Deletion — remove rows/columns if missing data is minimal (<5%) and random; (3) Imputation — replace with mean/median (numerical) or mode (categorical) for simple cases; (4) Advanced imputation — KNN imputation, MICE (Multiple Imputation by Chained Equations), or model-based imputation for complex cases. For outliers: (1) Identify using IQR method (values beyond 1.5*IQR from quartiles) or Z-score (>3 standard deviations); (2) Investigate — outliers may be data errors or genuine extreme values; (3) Handle by capping (Winsorization), transformation (log scale), or removal if confirmed errors. Document all decisions.', hint: 'Always understand why data is missing or extreme before deciding how to handle it.' },
        ],
    },

    'DevOps Engineering': {
        beginner: [
            { id: 1, level: 'beginner', type: 'conceptual', question: 'What is DevOps and what problems does it solve?', answer: 'DevOps is a set of practices that combines software development (Dev) and IT operations (Ops) to shorten the development lifecycle and deliver high-quality software continuously. It solves the traditional "wall of confusion" between developers who want to ship fast and operations teams who prioritize stability. Key practices include CI/CD pipelines, infrastructure as code, automated testing, monitoring, and collaboration culture. DevOps enables faster releases, fewer failures, quicker recovery from incidents, and better collaboration between teams. Tools like Jenkins, Docker, Kubernetes, and Terraform are central to DevOps workflows.', hint: 'DevOps bridges the gap between development speed and operational stability.' },
            { id: 2, level: 'beginner', type: 'conceptual', question: 'What is Docker and what problem does containerization solve?', answer: 'Docker is a platform for building, shipping, and running applications in containers. A container packages an application with all its dependencies (libraries, runtime, config) into a single portable unit. This solves the "it works on my machine" problem — containers run identically across development, staging, and production environments. Unlike virtual machines, containers share the host OS kernel, making them lightweight and fast to start. Key concepts: Dockerfile (instructions to build an image), Image (read-only template), Container (running instance of an image), and Docker Hub (registry for sharing images).', hint: 'Containers package everything an app needs to run consistently anywhere.' },
            { id: 3, level: 'beginner', type: 'coding', question: 'Write a Dockerfile for a Node.js application.', answer: 'FROM node:18-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --only=production\nCOPY . .\nEXPOSE 3000\nCMD ["node", "server.js"]\n\nKey decisions: use alpine for smaller image size, copy package.json first to leverage Docker layer caching (dependencies only reinstall when package.json changes), use npm ci instead of npm install for reproducible builds, and use EXPOSE to document the port. For development, add a .dockerignore file to exclude node_modules and .git from the build context.', hint: 'Copy package.json first, then run npm install, then copy source code — this optimizes layer caching.' },
        ],
        intermediate: [
            { id: 4, level: 'intermediate', type: 'conceptual', question: 'What is CI/CD and how does a typical pipeline work?', answer: 'CI (Continuous Integration) is the practice of automatically building and testing code every time a developer pushes changes. CD (Continuous Delivery/Deployment) extends this by automatically deploying tested code to staging or production. A typical pipeline: (1) Developer pushes code to Git; (2) CI server (GitHub Actions, Jenkins) triggers; (3) Install dependencies; (4) Run linting and unit tests; (5) Build Docker image; (6) Run integration tests; (7) Push image to registry; (8) Deploy to staging; (9) Run smoke tests; (10) Deploy to production (manual approval for Delivery, automatic for Deployment). This catches bugs early and enables multiple deployments per day.', hint: 'CI builds and tests; CD deploys — together they automate the path from code to production.' },
            { id: 5, level: 'intermediate', type: 'conceptual', question: 'What is Kubernetes and what problems does it solve?', answer: 'Kubernetes (K8s) is an open-source container orchestration platform that automates deploying, scaling, and managing containerized applications. Problems it solves: (1) Container scheduling — decides which node to run containers on based on resource availability; (2) Self-healing — automatically restarts failed containers and replaces unhealthy nodes; (3) Horizontal scaling — scales pods up/down based on CPU/memory metrics; (4) Service discovery and load balancing — routes traffic to healthy pods; (5) Rolling updates — deploys new versions with zero downtime; (6) Secret management — stores sensitive config separately from application code. Key objects: Pod, Deployment, Service, ConfigMap, Ingress.', hint: 'Kubernetes automates the operational tasks of running containers at scale.' },
            { id: 6, level: 'intermediate', type: 'coding', question: 'Write a GitHub Actions workflow to build and test a Node.js application.', answer: 'name: CI\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v3\n      - uses: actions/setup-node@v3\n        with:\n          node-version: 18\n          cache: npm\n      - run: npm ci\n      - run: npm test\n      - run: npm run build\n\nThis workflow triggers on every push and pull request, checks out code, sets up Node.js with caching, installs dependencies with npm ci, runs tests, and builds the project. Add environment secrets in GitHub repository settings and reference them as ${{ secrets.MY_SECRET }}.', hint: 'Use actions/checkout and actions/setup-node as the foundation for any Node.js workflow.' },
            { id: 7, level: 'intermediate', type: 'conceptual', question: 'What is Infrastructure as Code (IaC) and what are its benefits?', answer: 'Infrastructure as Code is the practice of managing and provisioning infrastructure (servers, networks, databases) through machine-readable configuration files rather than manual processes. Tools include Terraform (cloud-agnostic), AWS CloudFormation, and Pulumi. Benefits: (1) Version control — infrastructure changes are tracked in Git like application code; (2) Reproducibility — spin up identical environments consistently; (3) Automation — no manual clicking in cloud consoles; (4) Documentation — the code itself documents the infrastructure; (5) Disaster recovery — rebuild infrastructure quickly from code; (6) Cost management — easily destroy and recreate environments. Terraform uses HCL (HashiCorp Configuration Language) and supports AWS, GCP, Azure, and more.', hint: 'IaC treats infrastructure configuration the same way as application code — versioned, reviewed, automated.' },
        ],
        advanced: [
            { id: 8, level: 'advanced', type: 'conceptual', question: 'How would you implement a zero-downtime deployment strategy?', answer: 'Zero-downtime deployment strategies: (1) Rolling update — gradually replace old pods with new ones, Kubernetes does this by default; (2) Blue-Green deployment — run two identical environments, switch traffic from blue (current) to green (new) instantly, easy rollback by switching back; (3) Canary deployment — route a small percentage of traffic (e.g., 5%) to the new version, monitor metrics, gradually increase if healthy; (4) Feature flags — deploy code but hide new features behind flags, enable for specific users. Key requirements: health checks so load balancer only routes to healthy instances, database migrations must be backward compatible, and session state must be externalized (Redis) so any instance can serve any request.', hint: 'The key is ensuring the load balancer never routes traffic to unhealthy instances during the transition.' },
            { id: 9, level: 'advanced', type: 'conceptual', question: 'What is observability and what are its three pillars?', answer: 'Observability is the ability to understand the internal state of a system from its external outputs. The three pillars are: (1) Metrics — numerical measurements over time (CPU usage, request rate, error rate, latency). Tools: Prometheus, Grafana, Datadog. Use for alerting and dashboards; (2) Logs — timestamped records of discrete events. Tools: ELK stack (Elasticsearch, Logstash, Kibana), Loki. Use for debugging specific incidents; (3) Traces — records of a request as it flows through distributed services, showing latency at each step. Tools: Jaeger, Zipkin, AWS X-Ray. Use for identifying bottlenecks in microservices. Together they enable faster incident detection, diagnosis, and resolution.', hint: 'Metrics tell you something is wrong, logs tell you what happened, traces tell you where.' },
            { id: 10, level: 'advanced', type: 'conceptual', question: 'How do you secure a Kubernetes cluster in production?', answer: 'Key security practices: (1) RBAC — use Role-Based Access Control to grant least-privilege permissions to users and service accounts; (2) Network Policies — restrict pod-to-pod communication, only allow necessary traffic; (3) Pod Security Standards — prevent privileged containers, enforce read-only root filesystems; (4) Secrets management — use Kubernetes Secrets or external solutions like HashiCorp Vault, never hardcode secrets in images; (5) Image scanning — scan container images for vulnerabilities with Trivy or Snyk; (6) Admission controllers — use OPA/Gatekeeper to enforce policies; (7) Audit logging — enable API server audit logs; (8) Keep nodes and control plane updated; (9) Use private container registries; (10) Enable etcd encryption at rest.', hint: 'Security is layered — cover network, identity, workloads, secrets, and supply chain.' },
        ],
    },

    'UI/UX Design': {
        beginner: [
            { id: 1, level: 'beginner', type: 'conceptual', question: 'What is the difference between UI and UX design?', answer: 'UI (User Interface) design focuses on the visual and interactive elements of a product — colors, typography, buttons, icons, spacing, and layout. It is about how the product looks. UX (User Experience) design focuses on the overall experience a user has with a product — how easy it is to use, how it makes users feel, and whether it helps them achieve their goals. It is about how the product works. A product can have beautiful UI but poor UX (looks great but is confusing to use), or good UX but poor UI (easy to use but visually unappealing). Great products need both working together.', hint: 'UI is how it looks; UX is how it works and feels.' },
            { id: 2, level: 'beginner', type: 'conceptual', question: 'What is a user persona and why is it important in UX design?', answer: 'A user persona is a fictional representation of a target user based on research data — demographics, goals, behaviors, pain points, and motivations. Personas are created from user interviews, surveys, and analytics data. They are important because they keep the design team focused on real user needs rather than assumptions. When making design decisions, teams ask "would Sarah (our persona) understand this?" Personas prevent designing for yourself and help prioritize features. A typical persona includes a name, photo, age, job, goals, frustrations, and a quote that captures their mindset.', hint: 'Personas represent real users based on research, not assumptions.' },
            { id: 3, level: 'beginner', type: 'conceptual', question: 'What is wireframing and how does it differ from prototyping?', answer: 'A wireframe is a low-fidelity, schematic representation of a page layout — showing structure, content placement, and navigation without colors, fonts, or detailed visuals. It is like a blueprint. Wireframes are quick to create (pen and paper or tools like Balsamiq) and focus on layout and functionality. A prototype is a higher-fidelity, interactive simulation of the final product that demonstrates user flows and interactions. Prototypes can be low-fi (clickable wireframes in Figma) or high-fi (pixel-perfect with animations). Wireframes come first to validate structure; prototypes come later to test interactions and gather user feedback.', hint: 'Wireframes show structure; prototypes simulate interaction.' },
        ],
        intermediate: [
            { id: 4, level: 'intermediate', type: 'conceptual', question: 'What is a design system and what are its key components?', answer: 'A design system is a collection of reusable components, guidelines, and standards that enable teams to build consistent products efficiently. Key components: (1) Design tokens — variables for colors, typography, spacing, shadows; (2) Component library — reusable UI components (buttons, inputs, cards, modals) with defined states; (3) Pattern library — common UI patterns (navigation, forms, data tables); (4) Documentation — usage guidelines, do/don\'t examples, accessibility notes; (5) Brand guidelines — logo usage, voice and tone. Examples include Google\'s Material Design, Apple\'s Human Interface Guidelines, and Atlassian\'s Design System. Design systems reduce inconsistency, speed up design and development, and improve collaboration.', hint: 'A design system is a single source of truth for design decisions across a product.' },
            { id: 5, level: 'intermediate', type: 'conceptual', question: 'What is usability testing and how do you conduct it?', answer: 'Usability testing involves observing real users attempting to complete tasks with a product to identify usability problems. Process: (1) Define goals — what questions do you want answered?; (2) Recruit participants — 5 users typically reveal 85% of usability issues (Nielsen\'s rule); (3) Create tasks — realistic scenarios, not instructions (e.g., "Find and purchase a blue shirt" not "Click the shop button"); (4) Conduct sessions — observe without helping, note where users struggle; (5) Analyze findings — identify patterns across participants; (6) Prioritize and fix issues. Methods include moderated (facilitator present), unmoderated (remote, tools like UserTesting.com), and guerrilla testing (quick, informal). Always test with real users, not colleagues.', hint: 'Watch what users do, not what they say they would do.' },
            { id: 6, level: 'intermediate', type: 'conceptual', question: 'What are the key principles of accessibility in UI/UX design?', answer: 'Web accessibility (WCAG guidelines) ensures products are usable by people with disabilities. Key principles (POUR): (1) Perceivable — provide text alternatives for images (alt text), captions for videos, sufficient color contrast (4.5:1 ratio for normal text); (2) Operable — all functionality available via keyboard, no content that causes seizures, sufficient time to complete tasks; (3) Understandable — clear language, consistent navigation, helpful error messages; (4) Robust — compatible with assistive technologies like screen readers. Practical tips: never rely on color alone to convey information, ensure focus states are visible, use semantic HTML, and test with screen readers (NVDA, VoiceOver).', hint: 'Design for the full spectrum of human ability — visual, motor, cognitive, and auditory.' },
            { id: 7, level: 'intermediate', type: 'conceptual', question: 'What is the difference between qualitative and quantitative UX research?', answer: 'Quantitative research measures what users do with numbers — analytics data, A/B test results, survey ratings, task completion rates, and time-on-task. It answers "how many" and "how much" questions and is statistically significant with large sample sizes. Qualitative research explores why users behave as they do — user interviews, usability testing observations, diary studies, and contextual inquiry. It provides rich insights and uncovers motivations but with small samples (5-10 users). Best practice is to use both: quantitative data identifies that there is a problem (e.g., high drop-off on checkout page), qualitative research explains why (e.g., users are confused by the shipping options).', hint: 'Quantitative tells you what is happening; qualitative tells you why.' },
        ],
        advanced: [
            { id: 8, level: 'advanced', type: 'conceptual', question: 'How do you measure the success of a UX design?', answer: 'UX success is measured through a combination of metrics: (1) Behavioral metrics — task completion rate, error rate, time-on-task, clicks to complete a task; (2) Attitudinal metrics — SUS (System Usability Scale, 0-100 score), NPS (Net Promoter Score), CSAT (Customer Satisfaction); (3) Business metrics — conversion rate, retention rate, support ticket volume, revenue per user; (4) Engagement metrics — DAU/MAU ratio, session length, feature adoption rate. The HEART framework (Happiness, Engagement, Adoption, Retention, Task Success) by Google provides a structured approach. Always establish baseline metrics before redesigning so you can measure improvement.', hint: 'Combine behavioral data (what users do) with attitudinal data (what users feel).' },
            { id: 9, level: 'advanced', type: 'conceptual', question: 'What is Jobs-to-be-Done theory and how does it influence design?', answer: 'Jobs-to-be-Done (JTBD) is a framework that focuses on the underlying goal or "job" a user is trying to accomplish, rather than their demographic profile or product features. The idea: people "hire" products to do a job for them. Example: people don\'t buy a drill, they hire it to make a hole; they don\'t hire Spotify for music, they hire it to manage their mood. This influences design by shifting focus from features to outcomes — asking "what job is the user hiring this product to do?" and "what are the functional, emotional, and social dimensions of that job?" JTBD helps identify unmet needs, prioritize features, and craft better onboarding experiences.', hint: 'Focus on the outcome users want to achieve, not the features they use to achieve it.' },
            { id: 10, level: 'advanced', type: 'conceptual', question: 'How do you design for complex enterprise applications with many user types?', answer: 'Designing for enterprise complexity requires: (1) Role-based design — map all user types (admin, manager, analyst, viewer) and their distinct workflows and permissions; (2) Progressive disclosure — show only what each role needs, reveal complexity on demand; (3) Contextual navigation — adapt the interface based on the user\'s current task context; (4) Bulk operations — enterprise users manage many items, design for efficiency with multi-select, batch actions, and keyboard shortcuts; (5) Data density — enterprise users often prefer information-dense interfaces over consumer-style whitespace; (6) Customization — allow users to configure dashboards and workflows; (7) Onboarding for complex features — tooltips, empty states, and guided tours. Conduct extensive contextual inquiry to understand real workflows before designing.', hint: 'Enterprise design prioritizes efficiency and power over simplicity — users are experts in their domain.' },
        ],
    },

    'Mobile App Development': {
        beginner: [
            { id: 1, level: 'beginner', type: 'conceptual', question: 'What is the difference between native, hybrid, and cross-platform mobile development?', answer: 'Native development uses platform-specific languages — Swift/Objective-C for iOS and Kotlin/Java for Android. It provides the best performance and full access to device APIs but requires separate codebases. Hybrid development (Ionic, Cordova) wraps a web app in a native container — one codebase but limited native feel and performance. Cross-platform development (React Native, Flutter) uses a single codebase that compiles to native components — near-native performance with code sharing. React Native uses JavaScript and renders native components; Flutter uses Dart and its own rendering engine. Choose native for performance-critical apps, cross-platform for faster development with good performance.', hint: 'Consider performance, code sharing, and access to native device features.' },
            { id: 2, level: 'beginner', type: 'conceptual', question: 'What is React Native and how does it differ from React?', answer: 'React Native is a framework for building mobile apps using React and JavaScript. While React renders to the browser DOM using HTML elements (div, span, p), React Native renders to native mobile components (View, Text, Image, ScrollView) on iOS and Android. The JavaScript logic runs in a separate thread and communicates with the native layer via a bridge (or the new JSI architecture). Key differences: no CSS (uses StyleSheet API with similar properties), no HTML elements, navigation uses libraries like React Navigation, and you must handle platform differences (iOS vs Android). The React concepts — components, state, hooks, props — are identical.', hint: 'React Native uses the same React concepts but renders native mobile components instead of HTML.' },
            { id: 3, level: 'beginner', type: 'coding', question: 'Write a simple React Native component that displays a list of items.', answer: 'import React from "react"; import { View, Text, FlatList, StyleSheet } from "react-native"; const items = [{ id: "1", name: "Item 1" }, { id: "2", name: "Item 2" }]; export default function ItemList() { return ( <FlatList data={items} keyExtractor={item => item.id} renderItem={({ item }) => ( <View style={styles.item}><Text>{item.name}</Text></View> )} /> ); } const styles = StyleSheet.create({ item: { padding: 16, borderBottomWidth: 1, borderColor: "#eee" } }). Use FlatList instead of ScrollView for long lists — it only renders visible items (virtualization), improving performance significantly.', hint: 'Use FlatList for lists — it virtualizes rendering and is much more performant than ScrollView.' },
        ],
        intermediate: [
            { id: 4, level: 'intermediate', type: 'conceptual', question: 'How does navigation work in React Native applications?', answer: 'React Native does not have built-in navigation — the most popular library is React Navigation. Key navigators: (1) Stack Navigator — screens stack on top of each other with back button, like a browser history; (2) Tab Navigator — bottom or top tabs for switching between main sections; (3) Drawer Navigator — side menu that slides in. Navigation is set up with a NavigationContainer at the root. Navigate between screens using navigation.navigate("ScreenName", { params }). Access params with route.params. Deep linking allows opening specific screens from URLs or push notifications. Nested navigators (tabs inside a stack) handle complex app structures.', hint: 'React Navigation provides Stack, Tab, and Drawer navigators that can be nested.' },
            { id: 5, level: 'intermediate', type: 'conceptual', question: 'What are the key performance optimization techniques for React Native apps?', answer: 'Key optimizations: (1) Use FlatList/SectionList instead of ScrollView for long lists — they virtualize rendering; (2) Memoize components with React.memo and callbacks with useCallback to prevent unnecessary re-renders; (3) Use the new architecture (JSI/Fabric) for better JS-native communication; (4) Avoid inline styles — use StyleSheet.create() which optimizes style objects; (5) Use InteractionManager to defer heavy work until after animations; (6) Optimize images — use appropriate sizes, WebP format, and caching libraries like FastImage; (7) Enable Hermes JavaScript engine for faster startup; (8) Use the Flipper profiler and React DevTools to identify bottlenecks. Always profile before optimizing.', hint: 'Most performance issues come from unnecessary re-renders and unoptimized lists.' },
            { id: 6, level: 'intermediate', type: 'conceptual', question: 'How do you handle offline functionality in a mobile app?', answer: 'Offline support requires: (1) Local storage — AsyncStorage for simple key-value data, SQLite (via expo-sqlite) for structured data, or MMKV for high-performance storage; (2) State management — Redux Persist or Zustand with persistence to save app state locally; (3) Network detection — NetInfo library to detect connectivity changes; (4) Optimistic updates — update UI immediately, sync with server when online; (5) Queue system — store failed API requests and retry when connectivity returns; (6) Data sync strategy — decide what data to cache and for how long; (7) Conflict resolution — handle cases where offline changes conflict with server changes. Libraries like WatermelonDB provide full offline-first database solutions.', hint: 'Offline-first means designing for offline as the default, not as an edge case.' },
            { id: 7, level: 'intermediate', type: 'conceptual', question: 'What is Flutter and how does it compare to React Native?', answer: 'Flutter is Google\'s cross-platform framework using the Dart language. Unlike React Native which bridges to native components, Flutter uses its own rendering engine (Skia/Impeller) to draw every pixel — this means pixel-perfect consistency across platforms but a different look from native components. Advantages over React Native: better performance (no bridge), consistent UI across platforms, excellent animation support, and strong typing with Dart. Disadvantages: smaller ecosystem than React Native/JavaScript, Dart is less widely known, and larger app size. React Native has a larger community, JavaScript familiarity, and better integration with existing web codebases. Both are production-ready choices.', hint: 'Flutter draws its own UI; React Native uses native components — this is the fundamental difference.' },
        ],
        advanced: [
            { id: 8, level: 'advanced', type: 'conceptual', question: 'How do you implement push notifications in a React Native app?', answer: 'Push notifications require: (1) Setup — configure APNs (Apple Push Notification service) for iOS and FCM (Firebase Cloud Messaging) for Android; (2) Library — use Expo Notifications or React Native Firebase; (3) Permission — request notification permission from the user at an appropriate moment; (4) Token — get the device push token and send it to your backend; (5) Backend — store tokens per user and use FCM/APNs APIs to send notifications; (6) Handling — handle notifications when app is in foreground (show in-app), background (system notification), and killed state (open app to specific screen via deep link). For local notifications (no server), use scheduled notifications for reminders.', hint: 'Push notifications require coordination between your backend, FCM/APNs, and the app.' },
            { id: 9, level: 'advanced', type: 'conceptual', question: 'What is the React Native New Architecture and what problems does it solve?', answer: 'The old React Native architecture had a bridge — all communication between JavaScript and native code was serialized to JSON and passed asynchronously, causing performance bottlenecks. The New Architecture introduces: (1) JSI (JavaScript Interface) — allows JavaScript to directly reference and call native objects without serialization, enabling synchronous communication; (2) Fabric — new rendering system that makes the UI layer synchronous and supports concurrent React features; (3) TurboModules — lazy-loaded native modules that only initialize when needed, improving startup time; (4) Codegen — automatically generates type-safe native code from TypeScript interfaces. Together these eliminate the bridge bottleneck, enable better animations, and support React 18 concurrent features.', hint: 'The New Architecture replaces the async JSON bridge with direct synchronous JS-native communication.' },
            { id: 10, level: 'advanced', type: 'conceptual', question: 'How do you approach app store optimization and release management for mobile apps?', answer: 'Release management involves: (1) Versioning — use semantic versioning, increment build numbers for each submission; (2) Code signing — manage certificates and provisioning profiles (iOS) and keystore files (Android) securely; (3) Environment management — separate dev, staging, and production configs using react-native-config or Expo\'s app.config.js; (4) OTA updates — use Expo Updates or CodePush to push JavaScript bundle updates without app store review; (5) Beta testing — TestFlight (iOS) and Google Play Internal Testing for pre-release feedback; (6) CI/CD — automate builds with Fastlane, EAS Build, or Bitrise; (7) Crash monitoring — integrate Sentry or Firebase Crashlytics; (8) App Store Optimization (ASO) — optimize title, description, screenshots, and keywords for discoverability.', hint: 'Automate the build and release pipeline — manual app store submissions do not scale.' },
        ],
    },

    'AI/ML Engineering': {
        beginner: [
            { id: 1, level: 'beginner', type: 'conceptual', question: 'What is the difference between supervised, unsupervised, and reinforcement learning?', answer: 'Supervised learning trains a model on labeled data — input-output pairs — to learn a mapping function. Examples: classification (spam detection), regression (house price prediction). Unsupervised learning finds patterns in unlabeled data without predefined outputs. Examples: clustering (customer segmentation with K-means), dimensionality reduction (PCA). Reinforcement learning trains an agent to make decisions by rewarding desired behaviors and penalizing undesired ones — the agent learns through trial and error. Examples: game playing (AlphaGo), robotics, recommendation systems. Most real-world ML problems use supervised learning; unsupervised is used for exploration and preprocessing.', hint: 'Supervised has labels; unsupervised finds patterns; reinforcement learns from rewards.' },
            { id: 2, level: 'beginner', type: 'conceptual', question: 'What is overfitting and how do you prevent it?', answer: 'Overfitting occurs when a model learns the training data too well — including noise and random fluctuations — and performs poorly on new, unseen data. Signs: high training accuracy but low validation accuracy. Prevention techniques: (1) More training data — the most effective solution; (2) Regularization — L1 (Lasso) adds absolute value penalty, L2 (Ridge) adds squared penalty to the loss function; (3) Dropout — randomly deactivate neurons during training in neural networks; (4) Early stopping — stop training when validation loss starts increasing; (5) Cross-validation — use k-fold CV to get reliable performance estimates; (6) Simpler model — reduce model complexity (fewer layers, features); (7) Data augmentation — artificially increase training data variety.', hint: 'Overfitting means the model memorized training data instead of learning general patterns.' },
            { id: 3, level: 'beginner', type: 'coding', question: 'Write Python code to train a simple linear regression model using scikit-learn.', answer: 'from sklearn.linear_model import LinearRegression\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import mean_squared_error\nimport numpy as np\n\nX = np.array([[1],[2],[3],[4],[5]])\ny = np.array([2, 4, 5, 4, 5])\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)\n\ny_pred = model.predict(X_test)\nprint(f"MSE: {mean_squared_error(y_test, y_pred):.2f}")\nprint(f"Coefficient: {model.coef_[0]:.2f}, Intercept: {model.intercept_:.2f}")\n\nAlways split data before fitting to avoid data leakage. Use random_state for reproducibility.', hint: 'Always split data into train/test before fitting the model to get an honest performance estimate.' },
        ],
        intermediate: [
            { id: 4, level: 'intermediate', type: 'conceptual', question: 'What is the bias-variance tradeoff in machine learning?', answer: 'Bias is the error from incorrect assumptions in the learning algorithm — a high-bias model underfits, missing relevant patterns (e.g., fitting a line to non-linear data). Variance is the error from sensitivity to small fluctuations in training data — a high-variance model overfits, learning noise as patterns. The tradeoff: increasing model complexity reduces bias but increases variance; decreasing complexity increases bias but reduces variance. The goal is to find the sweet spot that minimizes total error (bias² + variance + irreducible noise). Techniques like regularization, ensemble methods (bagging reduces variance, boosting reduces bias), and cross-validation help navigate this tradeoff.', hint: 'Bias = underfitting (too simple); Variance = overfitting (too complex). Find the balance.' },
            { id: 5, level: 'intermediate', type: 'conceptual', question: 'What is the difference between bagging and boosting ensemble methods?', answer: 'Both are ensemble methods that combine multiple models for better performance. Bagging (Bootstrap Aggregating) trains multiple models in parallel on random subsets of training data and averages their predictions. It reduces variance and prevents overfitting. Random Forest is the most popular bagging algorithm. Boosting trains models sequentially — each model focuses on the errors of the previous one, with misclassified samples getting higher weights. It reduces bias and can achieve very high accuracy. Popular boosting algorithms: AdaBoost, Gradient Boosting, XGBoost, LightGBM. Bagging is more robust to outliers; boosting can overfit noisy data. XGBoost is often the go-to for structured/tabular data competitions.', hint: 'Bagging is parallel and reduces variance; boosting is sequential and reduces bias.' },
            { id: 6, level: 'intermediate', type: 'coding', question: 'Write Python code to evaluate a classification model with multiple metrics.', answer: 'from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report\n\ny_true = [0, 1, 1, 0, 1, 1, 0, 0, 1, 0]\ny_pred = [0, 1, 0, 0, 1, 1, 1, 0, 1, 0]\n\nprint(f"Accuracy: {accuracy_score(y_true, y_pred):.2f}")\nprint(f"Precision: {precision_score(y_true, y_pred):.2f}")\nprint(f"Recall: {recall_score(y_true, y_pred):.2f}")\nprint(f"F1 Score: {f1_score(y_true, y_pred):.2f}")\nprint(classification_report(y_true, y_pred))\n\nUse F1 score for imbalanced datasets. Precision = TP/(TP+FP), Recall = TP/(TP+FN). Choose metric based on business cost of false positives vs false negatives.', hint: 'Choose your metric based on the cost of false positives vs false negatives in your use case.' },
            { id: 7, level: 'intermediate', type: 'conceptual', question: 'What is feature engineering and why is it important?', answer: 'Feature engineering is the process of using domain knowledge to create, transform, or select input features that make machine learning algorithms work better. Techniques include: (1) Feature creation — combining existing features (e.g., age * income), extracting date components (day of week, month); (2) Encoding — one-hot encoding for categorical variables, label encoding for ordinal; (3) Scaling — StandardScaler (zero mean, unit variance) or MinMaxScaler for algorithms sensitive to scale (SVM, KNN, neural networks); (4) Handling missing values — imputation strategies; (5) Feature selection — remove irrelevant features using correlation analysis, feature importance, or recursive feature elimination. Good feature engineering often matters more than algorithm choice — "garbage in, garbage out."', hint: 'Better features beat better algorithms — domain knowledge is your most valuable tool.' },
        ],
        advanced: [
            { id: 8, level: 'advanced', type: 'conceptual', question: 'How do transformer models work and why did they revolutionize NLP?', answer: 'Transformers (introduced in "Attention Is All You Need", 2017) replaced RNNs for NLP tasks. Key innovation: the self-attention mechanism allows each token to attend to all other tokens in the sequence simultaneously, capturing long-range dependencies that RNNs struggled with. Architecture: encoder (processes input) and decoder (generates output) stacks of attention layers and feed-forward networks. Multi-head attention runs attention in parallel with different learned projections. Positional encoding adds sequence order information. Why revolutionary: (1) Parallelizable training (unlike sequential RNNs); (2) Better at long-range dependencies; (3) Scales with data and compute. BERT (encoder-only), GPT (decoder-only), and T5 (encoder-decoder) are all transformer variants that power modern LLMs.', hint: 'Self-attention lets every token look at every other token — this is what makes transformers powerful.' },
            { id: 9, level: 'advanced', type: 'conceptual', question: 'What is MLOps and what does a production ML pipeline look like?', answer: 'MLOps applies DevOps principles to machine learning to reliably deploy and maintain models in production. A production ML pipeline includes: (1) Data pipeline — automated data collection, validation (Great Expectations), and feature engineering; (2) Feature store — centralized repository for computed features (Feast, Tecton); (3) Model training — automated retraining triggered by data drift or schedule; (4) Experiment tracking — log parameters, metrics, and artifacts (MLflow, Weights & Biases); (5) Model registry — version and stage models (staging, production); (6) Serving — REST API (FastAPI + model), batch inference, or real-time streaming; (7) Monitoring — track data drift, model performance degradation, and prediction distribution; (8) Retraining triggers — automated pipeline when performance drops below threshold.', hint: 'MLOps is about making ML models reliable, reproducible, and maintainable in production.' },
            { id: 10, level: 'advanced', type: 'conceptual', question: 'What is model interpretability and what techniques are used to explain ML predictions?', answer: 'Model interpretability is the degree to which humans can understand the cause of a model\'s decision. Techniques: (1) Intrinsically interpretable models — linear regression (coefficients), decision trees (rules), logistic regression; (2) Feature importance — tree-based models provide built-in feature importance scores; (3) SHAP (SHapley Additive exPlanations) — game theory-based method that assigns each feature a contribution value for a specific prediction, works for any model; (4) LIME (Local Interpretable Model-agnostic Explanations) — approximates the model locally with an interpretable model; (5) Partial Dependence Plots (PDP) — show marginal effect of a feature on predictions; (6) Attention visualization — for transformer models, visualize attention weights. Interpretability is critical for regulated industries (finance, healthcare) and for debugging model failures.', hint: 'SHAP is the gold standard for explaining individual predictions from any model type.' },
        ],
    },

    'Product Management': {
        beginner: [
            { id: 1, level: 'beginner', type: 'conceptual', question: 'What does a product manager do and how is it different from a project manager?', answer: 'A product manager (PM) defines what to build and why — they own the product vision, strategy, and roadmap. They prioritize features based on user needs and business goals, work with designers and engineers to build the right thing, and measure success through metrics. A project manager focuses on how and when to build — managing timelines, resources, and execution to deliver projects on time and on budget. PMs are strategic and outcome-focused ("did we solve the user problem?"); project managers are tactical and output-focused ("did we ship on time?"). In tech companies, PMs often do both roles, but the core distinction is what vs how.', hint: 'PM defines what to build and why; project manager ensures it gets built on time.' },
            { id: 2, level: 'beginner', type: 'conceptual', question: 'What is a product roadmap and what should it include?', answer: 'A product roadmap is a strategic document that communicates the vision, direction, and progress of a product over time. It should include: (1) Vision and goals — where the product is heading and why; (2) Themes or initiatives — high-level areas of focus (e.g., "improve onboarding", "expand to mobile"); (3) Features or epics — major capabilities planned, organized by quarter or release; (4) Success metrics — how you will measure if initiatives succeeded; (5) Dependencies and risks — what could block progress. Roadmaps should be outcome-focused (solve user problems) not feature-focused (ship X feature). They are living documents that evolve based on learnings. Avoid committing to specific dates far in advance — use "Now, Next, Later" instead of rigid timelines.', hint: 'A roadmap shows direction and priorities, not a fixed schedule of features.' },
            { id: 3, level: 'beginner', type: 'conceptual', question: 'What is a user story and how do you write a good one?', answer: 'A user story is a short, simple description of a feature from the user\'s perspective. Format: "As a [user type], I want [goal] so that [benefit]." Example: "As a customer, I want to save my payment information so that I can checkout faster next time." Good user stories follow INVEST criteria: Independent (can be built separately), Negotiable (details can be discussed), Valuable (delivers user value), Estimable (team can estimate effort), Small (fits in a sprint), Testable (clear acceptance criteria). Include acceptance criteria — specific conditions that must be met for the story to be considered done. User stories keep the team focused on user value rather than technical implementation.', hint: 'User stories describe what the user wants to accomplish and why, not how to build it.' },
        ],
        intermediate: [
            { id: 4, level: 'intermediate', type: 'conceptual', question: 'How do you prioritize features when everything seems important?', answer: 'Prioritization frameworks help make objective decisions: (1) RICE — score each feature by Reach (how many users), Impact (how much it helps, 0.25-3x scale), Confidence (how sure you are, %), and Effort (person-months). RICE score = (R * I * C) / E. Higher scores = higher priority; (2) Value vs Effort matrix — plot features on 2x2 grid, prioritize high-value low-effort (quick wins); (3) Kano model — categorize features as basic (must-have), performance (more is better), or delighters (unexpected wow); (4) Opportunity scoring — ask users to rate importance and satisfaction, prioritize high importance + low satisfaction. Always tie back to business goals and user needs. Say no to good ideas that don\'t align with strategy.', hint: 'Use frameworks like RICE to make prioritization decisions data-driven and defensible.' },
            { id: 5, level: 'intermediate', type: 'conceptual', question: 'What is product-market fit and how do you know when you have achieved it?', answer: 'Product-market fit (PMF) means your product satisfies a strong market demand — you have built something people want and are willing to pay for. Signs of PMF: (1) Organic growth — users tell others without prompting, low CAC; (2) High retention — users keep coming back, low churn; (3) Users would be "very disappointed" if the product disappeared (Sean Ellis test — >40% threshold); (4) Struggling to keep up with demand; (5) Clear value proposition that resonates. Before PMF, focus on learning and iteration; after PMF, focus on scaling and optimization. Many startups fail by scaling before achieving PMF. Measure with cohort retention curves — they should flatten (not decay to zero) indicating a sticky product.', hint: 'PMF is when users love your product so much they tell others and keep using it.' },
            { id: 6, level: 'intermediate', type: 'conceptual', question: 'How do you conduct effective user interviews to gather product insights?', answer: 'Effective user interviews follow these principles: (1) Recruit the right users — target users who match your persona, not just anyone; (2) Ask open-ended questions — "Tell me about the last time you..." not "Would you use this feature?"; (3) Focus on past behavior, not hypothetical futures — what users say they will do differs from what they actually do; (4) Listen more than you talk — aim for 80/20 ratio; (5) Dig deeper with "why" — ask "why" 5 times to uncover root motivations; (6) Avoid leading questions — "What challenges do you face with X?" not "Don\'t you find X frustrating?"; (7) Record and take notes — you will miss details otherwise; (8) Look for patterns across 5-10 interviews. The goal is to understand problems, not validate solutions.', hint: 'Ask about past behavior, not hypothetical futures — "Show me" beats "Would you?"' },
            { id: 7, level: 'intermediate', type: 'conceptual', question: 'What metrics should a product manager track and why?', answer: 'Metrics depend on product stage and goals, but common categories: (1) Acquisition — signups, traffic sources, conversion rate from visitor to user; (2) Activation — % of users who complete key onboarding actions, time to first value; (3) Engagement — DAU/MAU ratio, session length, feature adoption rate; (4) Retention — cohort retention curves, churn rate, repeat usage; (5) Revenue — MRR, ARPU, LTV, CAC, LTV:CAC ratio; (6) Referral — viral coefficient, NPS. Use the AARRR (Pirate Metrics) framework. Avoid vanity metrics (total users) — focus on actionable metrics that inform decisions. Always segment metrics by user type, acquisition channel, or cohort to find insights. One North Star Metric should align the entire team.', hint: 'Track metrics across the full user journey — acquisition, activation, engagement, retention, revenue.' },
        ],
        advanced: [
            { id: 8, level: 'advanced', type: 'conceptual', question: 'How do you build and communicate a product strategy?', answer: 'A product strategy connects company vision to execution. Framework: (1) Vision — where you want the product to be in 3-5 years; (2) Goals — measurable objectives for the next year (OKRs); (3) Market analysis — TAM/SAM/SOM, competitive landscape, trends; (4) User insights — personas, jobs-to-be-done, pain points; (5) Strategic pillars — 3-5 themes that guide decisions (e.g., "expand to enterprise", "improve retention"); (6) Roadmap — how pillars translate to initiatives; (7) Success metrics — how you will measure progress. Communicate strategy through: written docs (strategy brief), presentations (quarterly reviews), and storytelling (connect features back to strategy). Good strategy is about making hard choices — saying no to opportunities that don\'t fit.', hint: 'Strategy is about making deliberate choices on where to play and how to win.' },
            { id: 9, level: 'advanced', type: 'conceptual', question: 'How do you manage stakeholder expectations and influence without authority?', answer: 'PMs must influence without direct authority. Techniques: (1) Build relationships — invest time understanding stakeholder goals and constraints; (2) Use data — back decisions with user research, metrics, and market analysis; (3) Tell stories — use customer anecdotes to make abstract problems concrete; (4) Create alignment — tie your proposals to company OKRs and stakeholder goals; (5) Involve early — bring stakeholders into the problem discovery phase, not just solution review; (6) Communicate proactively — regular updates prevent surprises; (7) Manage up — keep leadership informed of progress and blockers; (8) Say no gracefully — explain trade-offs and offer alternatives. When stakeholders disagree, facilitate a decision-making process (DACI framework) rather than trying to convince everyone.', hint: 'Influence through data, storytelling, and aligning your goals with stakeholder goals.' },
            { id: 10, level: 'advanced', type: 'conceptual', question: 'What is the difference between a product-led and sales-led go-to-market strategy?', answer: 'Product-led growth (PLG) uses the product itself as the primary driver of acquisition, conversion, and expansion — users can sign up and get value without talking to sales. Examples: Slack, Dropbox, Figma. Characteristics: freemium or free trial, self-serve onboarding, viral loops, usage-based pricing. PLG works when the product has low complexity, clear value, and network effects. Sales-led growth (SLG) relies on a sales team to drive deals — common for complex, high-touch enterprise products. Examples: Salesforce, SAP. Characteristics: demos and pilots, custom pricing, implementation support, relationship-driven. Many companies use hybrid models — PLG for SMB, SLG for enterprise. The choice depends on product complexity, deal size, and target customer.', hint: 'PLG: product sells itself. SLG: sales team sells the product. Choose based on complexity and deal size.' },
        ],
    },
};

/**
 * Returns domain-specific fallback questions.
 */
function getFallbackData(domain) {
    const domainData = domainFallbacks[domain];
    if (domainData) {
        return { domain, questions: domainData };
    }
    // If domain not found, return Frontend as default
    return { domain, questions: domainFallbacks['Frontend Development'] };
}

/**
 * Main AI service with fallback chain:
 * 1. Check in-memory cache
 * 2. Try Gemini API
 * 3. Fallback to OpenRouter API
 * 4. Fallback to domain-specific pre-generated questions
 */
export async function generateQuestions(domain) {
    // 1. Return cached result if available
    const cached = getCache(domain);
    if (cached) {
        console.log(`[Cache] Returning cached result for: "${domain}"`);
        return { ...cached, source: 'cache' };
    }

    // 2. Try Gemini
    try {
        console.log(`[Gemini] Attempting to generate questions for: "${domain}"`);
        const result = await callGemini(domain);
        setCache(domain, result);
        return { ...result, source: 'gemini' };
    } catch (geminiError) {
        console.warn(`[Gemini] Failed: ${geminiError.message}`);
    }

    // 3. Try OpenRouter
    try {
        console.log(`[OpenRouter] Attempting to generate questions for: "${domain}"`);
        const result = await callOpenRouter(domain);
        setCache(domain, result);
        return { ...result, source: 'openrouter' };
    } catch (openRouterError) {
        console.warn(`[OpenRouter] Failed: ${openRouterError.message}`);
    }

    // 4. Return domain-specific fallback data
    console.warn(`[Fallback] Both APIs failed. Returning pre-generated data for: "${domain}"`);
    const fallback = getFallbackData(domain);
    return { ...fallback, source: 'fallback' };
}
